name: Test Workflow

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    outputs:
      test_result:
        description: 'Success or failure'
        value: ${{ jobs.test.outputs.test_result }}

jobs:
  test:
    # ðŸ” åªå…è®¸ main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.set_status.outputs.status }}  # job è¾“å‡º

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run typecheck
      - run: npm run test

      # è®¾ç½® step è¾“å‡º
      - id: set_status
        run: echo "status=success" >> $GITHUB_OUTPUT
