name: Test Workflow

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    outputs:
      test_result:
        description: 'Success or failure'
        value: ${{ jobs.test.outputs.test_result }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.set_status.outputs.status }}  # job 输出

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

#      - run: npm ci
#      - run: npm run typecheck
#      - run: npm run test

      # 设置 step 输出
      - id: set_status
        run: echo "status=success" >> $GITHUB_OUTPUT
